---
name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format:check

      - name: Build
        run: npm run build
